---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      synced_folders: [["/netcalc/src", "/netcalc/src"]]
      network:
      - ["forwarded_port", {guest: 8888, host: 8888}]

suites:
  - name: default
    run_list:
      - recipe[netcalc::default]
    attributes:
