---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      synced_folders: [["/Users/chris.antenesse/repos/cookbooks/helot-cookbook/files/default", "/src"]]
      network:
      - ["private_network", {ip: "10.10.10.2"}]

suites:
  - name: default
    run_list:
      - recipe[netcalc::default]
    attributes:

